# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CPAN-Mini-Phalanx100
version:      0.01
version_from: lib/CPAN/Mini/Phalanx100.pm
installdirs:  site
requires:
    CPAN::Mini:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
